name: p5
description: A Dart implementation of the Processing API for Flutter.
version: 0.0.6
homepage: https://github.com/codeanticode/p5.dart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=0.2.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


